### ISSUE TITLE
Class 'Laravel\Passport\Passport' not found 

### ISSUE THREAD

**Issue by nalwa** [kayrules/lumen-passport-mongodb#1]
Hi,
I am getting error Class 'Laravel\Passport\Passport' not found  on php artisan migrate.

my composer.json looks-
 "require": {
        "php": ">=5.6.4",
        "laravel/lumen-framework": "5.4.*",
        "vlucas/phpdotenv": "~2.2",
        "ramsey/uuid": "^3.5",
        "league/fractal": "^0.15.0",      
        "moeen-basra/laravel-passport-mongodb": ">= 1.0",
        "kayrules/lumen-passport-mongodb": "^0.2.2",
        "barryvdh/laravel-cors": "^0.8.6",
        "illuminate/mail": "^5.4",
        "jenssegers/mongodb": "^3.2"
    },
Please help

**Comment by nalwa** [comment]
I am setting up environment fro rest Api with lumen -mongodb-oauth with passport.

**Comment by lucascardial** [comment]
Hi @nalwa!
I built a docker image based on php7.2 with nginx: https://cloud.docker.com/repository/docker/cardial/php7.2
my docker-compose:
````
version: '3'
services:
  lumen:
    container_name: "ms1"
    image: cardial/php7.2:nginx
    volumes:
      - ./:/var/www/html
    ports:
      - 8080:80
  mongodb:
    volumes:
      - ../volumes:/data/db
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - "27017:27017"
```
